# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_auto_20160713_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='close_binary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='closed_binary_ksize',
            field=models.CharField(blank=True, default=(5, 5), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='dilate_binary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='dilate_binary_ksize',
            field=models.CharField(blank=True, default=(5, 5), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='erode_binary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='erode_binary_ksize',
            field=models.CharField(blank=True, default=(5, 5), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='open_binary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='opend_binary_ksize',
            field=models.CharField(blank=True, default=(5, 5), max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='binary_threshold_threshold',
            field=models.IntegerField(default=128),
        ),
    ]
