# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0043_document_hist_equalize'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='shift_coords',
            field=models.CharField(blank=True, default=(0, 0), max_length=100, null=True),
        ),
    ]
