# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0044_auto_20160715_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='scale_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='scale_area_ratio',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='scale_linear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='scale_linear_ratio',
            field=models.IntegerField(default=1),
        ),
    ]
