# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_auto_20160715_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rotation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='rotation_degree',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='scale_area_ratio',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='document',
            name='scale_linear_ratio',
            field=models.FloatField(default=1),
        ),
    ]
